### PR TITLE
add more tools details incl install instructions

### PR DESCRIPTION
**Pull request by BenGardiner**

### CODE REVIEW

**Comment by Res260** [comment]
I think this change breaks our script 
image

**Comment by Res260** [comment]
It needs to be a yaml list else it wont work :/

**Comment by BenGardiner** [comment]
Ok I will put instructions somewhere else and just put a link here

**Comment by Res260** [comment]
That, or you can put it in one line too

**Comment by BenGardiner** [comment]
😂😅 yes. that's also an option

**Pull request merged**
