### PR TITLE
Some logic to display a 'stay-tuned' page instead of past event.

### PR DESCRIPTION
**Pull request by bvanheu**
Reduce the amount of work required to put a stay-tuned page.
A JavaScript solution (overlay?) might be more adequate tho.

### CODE REVIEW

**Comment by obilodeau** [comment]
I like the idea of more automation. I'm going to do this month the old school way but look at this branch for next month.

Thanks!

**Comment by obilodeau** [comment]
I just relooked at this and I'm going to try it soon.

From a visual review:

* I think capture blocks could be changed into {% assign var = ... %} for smaller and cleaner liquid construct. 
* Would be nice if **`$DATE`** could be automatically generated

**Comment by obilodeau** [comment]
Made some changes. What do you think?

One of the things I wish I could have done is generate the next "third Wednesday of the month" from the liquid engine but I couldn't figure it out.

Since we need to commit to trigger a change anyway, I figure that running a script (or changing it by hand) is not that bad...

**Comment by bvanheu** [comment]
LGTM

**Pull request merged**
